version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/server/database/db

  server:
    build:
      context: ./server
    container_name: server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/file-sharing

  client:
    build:
      context: ./client
    container_name: client
    ports:
      - "80:80"

volumes:
  mongo-data:
